### ISSUE TITLE
Test Scenario: Settings Page

### ISSUE THREAD

**Issue by jkva** [coyote-team/coyote-wp#102]
When using the settings page, the plugin should:

- be configurable using an endpoint and token;
- an invalid token and/or endpoint should be communicated to the user;
- when a valid profile is found, this should be communicated to the user;
- when the membership role is _below_ "editor", this should be communicated to the user and considered an invalid profile;
- when there is only one organization associated with a profile, this should automatically be picked;
- when there are multiple organizations associated with a profile, the user should be prompted to pick an organization;
- when an organization is changed from one to another, the user should be warned that this wipes existing data and they should import again.

**Comment by Pen-a11y** [comment]
Going through the settings page I have found that there are 3 of these scenarios that are not implemented

- an invalid token and/or endpoint should be communicated to the user;
- when a valid profile is found, this should be communicated to the user;
- when there are multiple organizations associated with a profile, the user should be prompted to pick an organization;

I also had some questions regarding the scenario:
- when an organization is changed from one to another, the user should be warned that this wipes existing data and they should import again.

As at the moment there is a warning that something will happen when the user changes organization, and is read as "Important: changing organization requires an import of coyote resources.", but this doesn't tell the user that this would wipe the existing data. I think that additional text should be added to tell the user explicitly what changing organizations could do. 

There are also 2 scenarios that at this time couldn't be tested due to issues with my Coyote docker container. 
- when there is only one organization associated with a profile, this should automatically be picked;
- when the membership role is below "editor", this should be communicated to the user and considered an invalid profile;

Me and James had talked about what could possibly be the issue, and were wondering if @jkva could possibly test creating the container on Windows, and see if this could be reason for why the script was not working correctly on my machine. The plan at the moment to bypass my issue is to spin up a droplet to use as a test Coyote site.

**Comment by Pen-a11y** [comment]
The 2 scenarios that couldn't be tested have now been tested.

- when there is only one organization associated with a profile, this should automatically be picked; is implemented successfully and does choose the only organization
- when the membership role is below "editor", this should be communicated to the user and considered an invalid profile;
Is not implemented correctly and the profile can be chosen, and the user is told that it was successful

**Comment by Pen-a11y** [comment]
All of the following scenarios have been implemented:
- an invalid token and/or endpoint should be communicated to the user;
When an invalid token or endpoint is given it is communicated as an admin notice to the user.
- when a valid profile is found, this should be communicated to the user;
When a valid profile is found it is communicated to the user as an admin notice and displays their role and name for the profile.
- when there are multiple organizations associated with a profile, the user should be prompted to pick an organization;
When there are multiple organizations they are prompted to pick an organization and the additional settings are not displayed until the user chooses an organization for the profile.
All of the scenarios are now implemented properly.
