### ISSUE TITLE
Missing Host URIs

### ISSUE THREAD

**Issue by NolanHill** [coyote-team/coyote-wp#73]
1. Uploaded [image](https://chsdmdev.wpengine.com/wp-admin/upload.php?item=38556) to media library
2. [Resource](https://staging.coyote.pics/organizations/40/representations/172632) showed up immediately in coyote
3. Added image to [blog post](https://chsdmdev.wpengine.com/2020/11/23/example-willi-smith-post/) and published post
4. Added image to [page](https://chsdmdev.wpengine.com/example-willi-smith-page/) and published page
5. BUG: [Resource](https://staging.coyote.pics/organizations/40/resources/316595) lists no Host URIs
6. Wrote and approved a description for the [resource](https://staging.coyote.pics/organizations/40/representations/172632) in Coyote
7. Alt text from Coyote is added to the images on wordpress

**Comment by jkva** [comment]
I suspect this happens because the image is already "known" as an attachment by coyote; the hash for the source uri already exists in the coyote table, so any coyote API call is not made to attempt to insert a resource.

To fix this, I'll include "known" resources in the batch creation API call as well. Thanks for reporting this.

**Comment by jkva** [comment]
Fixed via https://github.com/coyote-team/coyote-wp/commit/51bf4e07011c1857a09834d4ac118cdc0f39e0fc; now always defaulting to `https` for attachment URLs.
